language: java

services:
  - mysql
  - postgresql
  - rabbitmq
  - mongodb

addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

jdk:
  - oraclejdk8

env:
  matrix:
    - VAULT_VER=0.6.5
    - VAULT_VER=0.7.3
    - VAULT_VER=0.8.3
    - VAULT_VER=0.9.6
    - VAULT_VER=0.10.3
    - VAULT_VER=0.11.5
    - VAULT_VER=1.0.3
    - VAULT_VER=1.1.0

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

install:
  - mkdir -p download
  - test -f download/apache-cassandra-3.11.4-bin.tar.gz || wget https://archive.apache.org/dist/cassandra/3.11.4/apache-cassandra-3.11.4-bin.tar.gz -O download/apache-cassandra-3.11.4-bin.tar.gz
  - tar xzf download/apache-cassandra-3.11.4-bin.tar.gz
  - cp -f spring-cloud-vault-config-databases/src/test/resources/cassandra.yaml apache-cassandra-3.11.4/conf
  - apache-cassandra-3.11.4/bin/cassandra
  - src/test/bash/create_certificates.sh
  - src/test/bash/install_vault.sh
  - src/test/bash/install_consul.sh
  - src/test/bash/local_run_vault.sh &
  - src/test/bash/local_run_consul.sh &
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo service rabbitmq-server restart

before_script:
  - mysql -e "CREATE USER 'springvault' IDENTIFIED by 'springvault';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'springvault'@'%' WITH GRANT OPTION;";
  - psql -U postgres -c "CREATE ROLE springvault WITH LOGIN PASSWORD 'springvault' CREATEROLE CREATEUSER;"
  - |-
    mongo admin --eval  "db.createUser({user: 'springvault', pwd:'springvault', roles:['root']});"
  - sleep 30 # wait until Cassandra is up
  - apache-cassandra-3.11.4/bin/cqlsh localhost -u cassandra -p cassandra -e "CREATE USER 'springvault' WITH PASSWORD 'springvault' SUPERUSER"

script: mvn clean verify -Pspring,java8

after_script:
  - apache-cassandra-3.11.4/bin/nodetool stopdaemon
  - pkill vault
  - pkill consul

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'download'
